import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { defineConfig } from 'wxt';

const require = createRequire(import.meta.url);

/**
 * Absolute path to one of ORT's non-bundled ESM builds.
 *
 * Resolved through the package's own entry rather than hard-coded, but it has to be
 * an absolute *file* path: `onnxruntime-web` does not export `./dist/*`, so an alias
 * pointing at a subpath is unresolvable.
 */
function ortBuild(file: string): string {
  return join(
    // Resolves through the "require" condition to dist/ort.min.js, whose directory is
    // what we actually want. `onnxruntime-web/package.json` is not exported either.
    dirname(require.resolve('onnxruntime-web')),
    file,
  );
}

/**
 * Which ORT build each target gets, and therefore which WASM binary it needs.
 *
 * Chrome can use WebGPU, so it gets the `jsep` build: WebGPU and WASM execution
 * providers in one 27 MB binary. Firefox has no WebGPU, so the same file would ship
 * 14 MB of code that can never run — it gets the plain WASM build (13 MB) instead.
 * `runtime.ts` already decides at load time which provider to ask for, and on
 * Firefox that decision was always "wasm".
 */
const ORT_TARGETS = {
  chrome: { entry: 'ort.min.mjs', keep: 'ort-wasm-simd-threaded.jsep.' },
  firefox: { entry: 'ort.wasm.min.mjs', keep: 'ort-wasm-simd-threaded.' },
} as const;

function ortFor(browser: string) {
  return browser === 'firefox' ? ORT_TARGETS.firefox : ORT_TARGETS.chrome;
}

// https://wxt.dev/api/config.html
export default defineConfig({
  targetBrowsers: ['chrome', 'firefox'],
  manifestVersion: 3,

  hooks: {
    /**
     * `public/` holds both ORT binaries so either target can be built without a
     * re-fetch. Only one of them is reachable at runtime, so drop the other before
     * it is copied — otherwise every build ships 40 MB of WASM to run 13.
     */
    'build:publicAssets'(wxt, files) {
      const { keep } = ortFor(wxt.config.browser);
      for (let i = files.length - 1; i >= 0; i--) {
        const name = files[i]!.relativeDest.replace(/\\/g, '/');
        if (!name.startsWith('ort/ort-wasm')) continue;
        // `keep` is a prefix of both names for Chrome's jsep pair, so match the
        // exact stem: "…threaded." must not also accept "…threaded.jsep.".
        const stem = name.slice('ort/'.length).replace(/(wasm|mjs)$/, '');
        if (stem !== keep) files.splice(i, 1);
      }
    },
  },

  vite: ({ browser }) => ({
    resolve: {
      alias: [
        {
          // ORT's default export is the "bundle" build, which inlines the wasm loader
          // and makes Vite emit its own hashed copy of the binary — on top of the one
          // we stage in public/ort/. Point at a non-bundled build instead: it fetches
          // both loader and binary from `ort.env.wasm.wasmPaths`, so exactly one copy
          // ships. Verified by checking the build output for stray .wasm files.
          //
          // Anchored: the replacement would otherwise match its own output and recurse.
          find: /^onnxruntime-web$/,
          replacement: ortBuild(ortFor(browser).entry),
        },
      ],
    },
  }),

  manifest: ({ browser }) => ({
    name: 'PrivAgent — privacy-preserving vision agent',
    description:
      'Reads the page with on-device models, redacts faces, passwords and PII before any network request, and only sends sanitized context to the server.',

    permissions: [
      // Read the active tab's pixels and message its content script.
      'tabs',
      'activeTab',
      // Inject the content script into tabs that were already open.
      'scripting',
      // storage.session holds the profile in memory only; nothing is written to disk.
      'storage',
      // Chrome's side panel API. Firefox uses sidebar_action, generated by WXT.
      ...(browser === 'chrome' ? ['sidePanel'] : []),
    ],

    // captureVisibleTab needs host access to the tab being captured, and the agent
    // has to work on any site the user opens — that is the whole point.
    host_permissions: ['<all_urls>'],

    // MV3 forbids remotely hosted code. onnxruntime-web's WASM is bundled into the
    // extension, so the pages that run models need 'wasm-unsafe-eval' (CLAUDE.md).
    content_security_policy: {
      extension_pages: "script-src 'self' 'wasm-unsafe-eval'; object-src 'self';",
    },

    ...(browser === 'firefox'
      ? {
          browser_specific_settings: {
            gecko: {
              id: 'privagent@sih.local',
              strict_min_version: '115.0',
              // Required by AMO since Nov 2025. "none" is the literal truth here:
              // the extension transmits only sanitized, tokenized context, and
              // never PII, telemetry or analytics.
              //
              // `web-ext lint` warns that this key needs Firefox 140 while our floor
              // is 115. That is expected and deliberate: an unknown manifest key is
              // ignored by older Firefox, so keeping 115 costs nothing and keeps the
              // extension installable a year further back. 115 is the real floor —
              // it is where `storage.session` landed.
              data_collection_permissions: { required: ['none'] },
            },
          },
        }
      : {}),
  }),
});
