import { defineConfig } from 'wxt';

// https://wxt.dev/api/config.html
export default defineConfig({
  targetBrowsers: ['chrome', 'firefox'],
  manifestVersion: 3,

  manifest: ({ browser }) => ({
    name: 'PrivAgent — privacy-preserving vision agent',
    description:
      'Reads the page with on-device models, redacts faces, passwords and PII before any network request, and only sends sanitized context to the server.',

    permissions: [
      // Read the active tab's pixels and message its content script.
      'tabs',
      'activeTab',
      // Inject the content script into tabs that were already open.
      'scripting',
      // storage.session holds the profile in memory only; nothing is written to disk.
      'storage',
      // Chrome's side panel API. Firefox uses sidebar_action, generated by WXT.
      ...(browser === 'chrome' ? ['sidePanel'] : []),
    ],

    // captureVisibleTab needs host access to the tab being captured, and the agent
    // has to work on any site the user opens — that is the whole point.
    host_permissions: ['<all_urls>'],

    // MV3 forbids remotely hosted code. onnxruntime-web's WASM is bundled into the
    // extension, so the pages that run models need 'wasm-unsafe-eval' (CLAUDE.md).
    content_security_policy: {
      extension_pages: "script-src 'self' 'wasm-unsafe-eval'; object-src 'self';",
    },

    ...(browser === 'firefox'
      ? {
          browser_specific_settings: {
            gecko: {
              id: 'privagent@sih.local',
              strict_min_version: '115.0',
              // Required by AMO since Nov 2025. "none" is the literal truth here:
              // the extension transmits only sanitized, tokenized context, and
              // never PII, telemetry or analytics.
              data_collection_permissions: { required: ['none'] },
            },
          },
        }
      : {}),
  }),
});
