/**
 * Saving the vault on this device, encrypted — only when the user turns it on.
 *
 * Until now the vault lived in memory and was gone when the browser closed, so the
 * user retyped their details every time. That was the safe default, and it is still
 * the default. "Remember on this device" is the user's choice to trade a little of
 * it for never retyping anything.
 *
 * What is saved: the user's own data — the profile and the answers it has learned
 * (Vault.backup). Never a value that was only seen on a page.
 *
 * How (D36):
 *   - AES-GCM-256 with a fresh 96-bit IV on every save.
 *   - The key is generated by WebCrypto as **non-extractable** and kept in the
 *     extension's IndexedDB. Script can use it to decrypt, but no script — ours
 *     included — can read its bytes out, so it cannot be copied off the machine.
 *   - The ciphertext is kept in `storage.local`. The plaintext never touches disk.
 *
 * What this does not protect against, stated plainly: someone who can run code as
 * this extension, on this browser profile, can decrypt it — as they could the
 * browser's own saved addresses. It protects the vault from being read off the
 * disk, from backups and sync of the profile folder, and from any other extension
 * or web page. "Forget" deletes the key and the ciphertext together.
 *
 * The crypto is separated from the storage (`VaultStores`) so it can be tested in
 * Node against in-memory stores; `browserStores` is the real one.
 */

import type { VaultBackup } from './vault';

export interface SealedBlob {
  /** Base64 of the 12-byte IV. */
  iv: string;
  /** Base64 of the AES-GCM ciphertext, tag included. */
  data: string;
}

export interface VaultStores {
  getKey(): Promise<CryptoKey | undefined>;
  putKey(key: CryptoKey): Promise<void>;
  getBlob(): Promise<SealedBlob | undefined>;
  putBlob(blob: SealedBlob): Promise<void>;
  /** Delete the key and the ciphertext. */
  clear(): Promise<void>;
}

async function vaultKey(stores: VaultStores, create: boolean): Promise<CryptoKey | undefined> {
  const existing = await stores.getKey();
  if (existing || !create) return existing;
  const key = await crypto.subtle.generateKey(
    { name: 'AES-GCM', length: 256 },
    false, // non-extractable: usable, never readable
    ['encrypt', 'decrypt'],
  );
  await stores.putKey(key);
  return key;
}

/** Encrypt the backup and save it, replacing any earlier one. */
export async function sealVault(backup: VaultBackup, stores: VaultStores): Promise<void> {
  const key = (await vaultKey(stores, true))!;
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const plain = new TextEncoder().encode(JSON.stringify(backup));
  const sealed = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, plain);
  await stores.putBlob({ iv: toBase64(iv), data: toBase64(new Uint8Array(sealed)) });
}

/**
 * Decrypt the saved vault. Undefined when nothing is saved — or when it cannot be
 * read (the key was cleared with the site data, or the blob was tampered with,
 * which AES-GCM's tag detects). Never throws: a vault that will not open is an
 * empty vault, not a broken panel.
 */
export async function openVault(stores: VaultStores): Promise<VaultBackup | undefined> {
  try {
    const blob = await stores.getBlob();
    if (!blob) return undefined;
    const key = await vaultKey(stores, false);
    if (!key) return undefined;
    const plain = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv: fromBase64(blob.iv) },
      key,
      fromBase64(blob.data),
    );
    const backup = JSON.parse(new TextDecoder().decode(plain)) as VaultBackup;
    return backup?.v === 1 ? backup : undefined;
  } catch {
    return undefined;
  }
}

export async function forgetVault(stores: VaultStores): Promise<void> {
  await stores.clear();
}

/* ---------------- the real stores ---------------- */

const DB_NAME = 'privagent-vault';
const DB_STORE = 'keys';
const KEY_ID = 'vault-key';
const BLOB_KEY = 'privagent.vault.sealed';

function database(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, 1);
    request.onupgradeneeded = () => request.result.createObjectStore(DB_STORE);
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

async function keyStore<T>(mode: IDBTransactionMode, run: (store: IDBObjectStore) => IDBRequest<T>): Promise<T> {
  const db = await database();
  try {
    return await new Promise<T>((resolve, reject) => {
      const request = run(db.transaction(DB_STORE, mode).objectStore(DB_STORE));
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
    });
  } finally {
    db.close();
  }
}

/**
 * IndexedDB holds the key because it can store a CryptoKey object as it is — which
 * is what keeps it non-extractable. `storage.local` only takes JSON, so a key kept
 * there would have to be exported first, and then anyone reading the disk has it.
 */
export function browserStores(): VaultStores {
  return {
    getKey: () => keyStore<CryptoKey | undefined>('readonly', (s) => s.get(KEY_ID)),
    putKey: async (key) => void (await keyStore('readwrite', (s) => s.put(key, KEY_ID))),
    getBlob: async () => {
      const stored = await browser.storage.local.get(BLOB_KEY);
      return stored?.[BLOB_KEY] as SealedBlob | undefined;
    },
    putBlob: (blob) => browser.storage.local.set({ [BLOB_KEY]: blob }),
    clear: async () => {
      await browser.storage.local.remove(BLOB_KEY);
      await keyStore('readwrite', (s) => s.delete(KEY_ID));
    },
  };
}

/* ---------------- base64 ---------------- */

function toBase64(bytes: Uint8Array): string {
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function fromBase64(text: string): Uint8Array<ArrayBuffer> {
  const binary = atob(text);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}
